In [10]:
import pandas as pd
import numpy as np
import zipfile as zp
zf = zp.ZipFile('external_datasets.zip')
#read in data and change into dataframe
cities_df = pd.read_csv(zf.open("external_datasets/cities_2010.csv"), encoding = "ISO-8859-1")
house_df = pd.read_csv(zf.open("external_datasets/housing.csv"), encoding = "ISO-8859-1")
income_df = pd.read_csv(zf.open("external_datasets/income.csv"), encoding = "ISO-8859-1")
poverty_df = pd.read_csv(zf.open("external_datasets/poverty.csv"), encoding = "ISO-8859-1")
age_df = pd.read_csv(zf.open("external_datasets/median_age.csv"), encoding = "ISO-8859-1")

# rename features
income_df.columns = ['GEO.id', 'GEO.id2', 'GEO.display-label', 'GCT_STUB.target-geo-id',
       'GCT_STUB.target-geo-id2', 'GCT_STUB.display-label',
       'GCT_STUB.display-label.1', 'income', 'income_margin_error']
poverty_df.columns = ['GEO.id', 'GEO.id2', 'GEO.display-label', 'GCT_STUB.target-geo-id',
       'GCT_STUB.target-geo-id2', 'GCT_STUB.display-label',
       'GCT_STUB.display-label.1', 'poverty_rate', 'poverty_margin_error']
age_df.columns = ['GEO.id', 'GEO.id2', 'GEO.display-label', 'GCT_STUB.target-geo-id',
       'GCT_STUB.target-geo-id2', 'GCT_STUB.display-label',
       'GCT_STUB.display-label.1', 'Median_age', 'age_margin_error']
cities_df.columns = ['GEO.id', 'GEO.id2', 'GEO.display-label', 'GCT_STUB.target-geo-id',
       'GCT_STUB.target-geo-id2', 'GCT_STUB.display-label',
       'GCT_STUB.display-label.1', 'Population', 'Housing units', 'Area in square miles - Total area', 'Area in square miles - Water area',
       'Area in square miles - Land area', 'Density per square mile of land area - Population', 'Density per square mile of land area - Housing units']

# merge dataframe
def merge_gis_data(df_list):
    final = df_list[0]
    for i in range(1,len(df_list)):
        final = pd.merge(final,df_list[i], how='outer', on='GCT_STUB.target-geo-id')
    return final

df_list = [cities_df,income_df,poverty_df,age_df]
finalized_df = merge_gis_data(df_list)

In [17]:
finalized_df.head()

,GEO.display-label_x,GCT_STUB.target-geo-id,GCT_STUB.display-label_x,GCT_STUB.display-label.1_x,Population,Housing units,Area in square miles - Total area,Area in square miles - Water area,Area in square miles - Land area,Density per square mile of land area - Population,...,GEO.display-label_x,GCT_STUB.display-label_x,GCT_STUB.display-label.1_x,poverty_rate,poverty_margin_error,GEO.display-label_y,GCT_STUB.display-label_y,GCT_STUB.display-label.1_y,Median_age,age_margin_error
3,United States,1600000US0100100,United States - Alabama - Abanda CDP,Abanda CDP,192,79,3.01,0.01,3.00,64.0,...,United States,United States - Alabama - Abanda CDP,Abanda CDP,35.7,44.6,United States,United States - Alabama - Abanda CDP,Abanda CDP,70.6,18.9
4,United States,1600000US0100124,United States - Alabama - Abbeville city,Abbeville city,2688,1255,15.58,0.04,15.54,172.9,...,United States,United States - Alabama - Abbeville city,Abbeville city,21.8,7.7,United States,United States - Alabama - Abbeville city,Abbeville city,46.6,8.4
5,United States,1600000US0100460,United States - Alabama - Adamsville city,Adamsville city,4522,1990,25.14,0.01,25.13,180.0,...,United States,United States - Alabama - Adamsville city,Adamsville city,19.1,7.0,United States,United States - Alabama - Adamsville city,Adamsville city,36.2,2.2
6,United States,1600000US0100484,United States - Alabama - Addison town,Addison town,758,351,3.80,0.03,3.77,201.3,...,United States,United States - Alabama - Addison town,Addison town,24.3,21.9,United States,United States - Alabama - Addison town,Addison town,42.4,6.3
7,United States,1600000US0100676,United States - Alabama - Akron town,Akron town,356,205,0.69,0.01,0.69,518.5,...,United States,United States - Alabama - Akron town,Akron town,20.9,10.4,United States,United States - Alabama - Akron town,Akron town,50.8,17.5

In [11]:
# drop features
drops = ["GEO.id_x","GEO.id_y","GEO.id2_x","GEO.id2_y","GCT_STUB.target-geo-id2_x","GCT_STUB.target-geo-id2_y"]
finalized_df = finalized_df.drop(drops,1)

In [14]:
# drop state info
finalized_df = finalized_df[finalized_df["GCT_STUB.target-geo-id"].str.len() == 16]

In [21]:
finalized_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29600 entries, 3 to 29653
Data columns (total 26 columns):
GEO.display-label_x                                     29521 non-null object
GCT_STUB.target-geo-id                                  29600 non-null object
GCT_STUB.display-label_x                                29521 non-null object
GCT_STUB.display-label.1_x                              29521 non-null object
Population                                              29521 non-null object
Housing units                                           29521 non-null object
Area in square miles - Total area                       29521 non-null object
Area in square miles - Water area                       29521 non-null object
Area in square miles - Land area                        29521 non-null object
Density per square mile of land area - Population       29521 non-null object
Density per square mile of land area - Housing units    29521 non-null object
GEO.display-label_y                                     29509 non-null object
GCT_STUB.display-label_y                                29509 non-null object
GCT_STUB.display-label.1_y                              29509 non-null object
income                                                  29509 non-null object
income_margin_error                                     29509 non-null object
GEO.display-label_x                                     29517 non-null object
GCT_STUB.display-label_x                                29517 non-null object
GCT_STUB.display-label.1_x                              29517 non-null object
poverty_rate                                            29517 non-null object
poverty_margin_error                                    29517 non-null object
GEO.display-label_y                                     29517 non-null object
GCT_STUB.display-label_y                                29517 non-null object
GCT_STUB.display-label.1_y                              29517 non-null object
Median_age                                              29517 non-null object
age_margin_error                                        29517 non-null object
dtypes: object(26)
memory usage: 6.1+ MB

In [19]:
drops1 = ["GCT_STUB.display-label_x","GCT_STUB.display-label_y","GCT_STUB.display-label.1_x","GCT_STUB.display-label.1_y","GCT_STUB.display-label_y"]
finalized_df = finalized_df.drop(drops,1)